### PR TITLE
Allow suggestions to re-render while interacting with the component.

### PR DESCRIPTION
**Pull request by JAndritsch**
Fixes a bug introduced by PR #123.

### CODE REVIEW

**Comment by prakhar1989** [comment]
This looks good - thanks! If it's not too much work, do you mind adding a test case for this to test? Will help us in catching these issues earlier.

**Comment by JAndritsch** [comment]
Sure thing!

**Comment by JAndritsch** [comment]
Done. Hope this is adequate coverage.

**Comment by prakhar1989** [comment]
Awesome - thanks a ton. Merging this now.

**Pull request merged**
