### PR TITLE
Added fuzzy search

### PR DESCRIPTION
**Pull request by Tyratox**
#119

### CODE REVIEW

**Comment by Tyratox** [comment]
Not sure why 3 tests fail, the two lines I changed don't interact with the component state from what I can see?

**Comment by prakhar1989** [comment]
The master branch of the repo is currently in a "build failing" state which is stopping me from accepting any new PRs (& releasing new version on NPM). Unfortunately, I've been super swamped at work & have not been able to investigate what's failing the build. I'd suggest waiting until that issue is resolved so that tests on your PR passes.

Also, much thanks for sending the PR. 👍

**Comment by Tyratox** [comment]
Oh I see. Yeah, in that case the PRs have to wait. I hope you are soon able to get things sorted at work :)

If anyone else wants to use the fuzzy search beforehand, just add the property `handleFilterSuggestions` to the `ReactTags` component with the function

    import fuzzy from 'fuzzy';
    
    const fuzzySearch = (query, suggestions) => {
        return fuzzy.filter(query, suggestions).map(function(item){
            return item.string;
        });
    }

**Comment by mrdannael** [comment]
@Tyratox can you rebase with master branch and fix your tests? :smiley:

**Comment by Tyratox** [comment]
Of course :)

**Comment by mrdannael** [comment]
Do not commit `dist/` and `dist-modules/` files. I wonder why files like i.e. `Readme.md` are marked as changed. Master already have those changes so it's nothing new though.

**Comment by Tyratox** [comment]
I'm sorry, didn't see that.
That's something I wondered as well, maybe I messed up rebasing?

**Comment by mrdannael** [comment]
Ok. I'll close this PR. Just make another with your changes :).
And maybe it's a good way to give any user to choose if he wants to use `fuzzy` search or the standard one by setting boolean value. In example fuzzy will be by default but with `fuzzy={false}` the standard search will be used. 

Anyway, if it's ok just try to make another PR only with your changes.

**Pull request closed without merging**
