### PR TITLE
Allow user to specify custom class names on the component

### PR DESCRIPTION
**Pull request by bitdivision**
Fixes issue #32.

One potential issue is that this will not merge the defaultProps with the passed class names. I'm not sure if this is a probable use-case but can add if required.

### CODE REVIEW

**Comment by prakhar1989** [comment]
This looks great!

> One potential issue is that this will not merge the defaultProps with the passed class names.

Let me know if I getting this right - you mean the user will have to either pass all custom classes or stick with the default ones right? I think it makes sense if we merge the default class object with the custom one so that the user can use the lib with minimum configuration. 

PS: [Lodash](https://lodash.com/docs#merge) already comes with a merge function that you can use.

**Comment by bitdivision** [comment]
Yeah, that's exactly what I meant. I hadn't noticed that lodash was already in there. I'll fix it up this evening probably.

**Comment by prakhar1989** [comment]
Sure :+1:

**Comment by cklab** [comment]
@bitdivision any plans to wrap up the PR?

**Comment by bitdivision** [comment]
@cklab 

Sorry for the delay, will finish this off tomorrow.

**Comment by sapegin** [comment]
@bitdivision @prakhar1989 It would be ver cool to have this merged.

**Comment by bitdivision** [comment]
@prakhar1989 I've added the functionality to merge default classnames. It's not the cleanest solution, since it stores classnames in state, but I couldn't see a nicer way of doing it.

Sorry about the rebase, probably should have merged instead.

**Comment by prakhar1989** [comment]
@bitdivision Don't worry about it. Thanks for the PR :wink:

**Pull request merged**
