### PR TITLE
fix: Fix #508 (Changing the suggestions prop doesn't trigger an update)

### LINKED ISSUE #508: Changing the suggestions prop doesn't trigger an update
Updating the `suggestions` prop (asynchronously) doesn't re-render the suggestions accordingly.

Demo: https://react-tag-input-ncvrjj.stackblitz.io
Here we change the `suggestions` prop 500ms after each input.

### Expected
When changing the `suggestions` prop the Suggestions component rerenders accordingly.

### Actual
The Suggestions component is rerendered eventually, but with an outdated state. (See demo)

### Notes
Last working version: `6.0.2`

### PR DESCRIPTION
**Pull request by dcsaszar**
The bots forced me to add a small refactoring to make the code climate green again.

### CODE REVIEW

**Comment by ad1992** [comment]
@dcsaszar thanks for your contribution, can you rebase your branch with master ?

**Comment by dcsaszar** [comment]
@ad1992 done.

**Comment by brymon68** [comment]
Can we please merge this pull request for release?

**Comment by apepper** [comment]
Any news on this PR? It would be great if this gets merged.

**Comment by apepper** [comment]
@mrdannael, @prakhar1989 or @ad1992: Could you merge this PR before the stale bot closes this useful pull-request?

**Comment by apepper** [comment]
Maybe we should ask `greenkeeper` to merge this PR 😸.

**Comment by apepper** [comment]
Thank you @ad1992 for merging this PR and releasing a new version!

**Pull request merged**
