### PR TITLE
Add name, id and maxLength props to input field

### PR DESCRIPTION
**Pull request by StefanFeser**
I'm using your lib in a project and it would be nice to have those attributes on the input field. 

See in #107

### CODE REVIEW

**Comment by prakhar1989** [comment]
Hi @StefanFeser, can you update the README changes associated with this update in the API?

**Comment by StefanFeser** [comment]
Hey @prakhar1989, sure!

**Comment by kobeaerts** [comment]
Any idea when this will be merged?

**Comment by prakhar1989** [comment]
Hey folks, sorry to keep you waiting on this. This looks great - merging it right away. 

Will take some time to do the release though, I'll test it bit and do it. 

Hope that makes sense.

**Comment by kobeaerts** [comment]
Hey @prakhar1989, any idea when the tag is gonna be ready? I kinda have a large project going live tomorrow, so if you don't find the time i'll use a workaround!

**Comment by mtxxxx** [comment]
@prakhar1989, could you release dist files that responded this issue?

**Comment by prakhar1989** [comment]
Hey everyone, (finally) released these changes on [NPM](https://www.npmjs.com/package/react-tag-input) (v4.6.3). Really really sorry for keeping all of you hanging for this long.

Also, tons of thanks to @teldosas for fixing the issue with broken builds.

Enjoy and Happy Easter!

**Pull request merged**
