### PR TITLE
add labelField prop option

### PR DESCRIPTION
**Pull request by beeant**
add labelField option for the property name of `tags collection` to render as an option / item label (default to `text`

### CODE REVIEW

**Comment by prakhar1989** [comment]
Hi @beeant! Can you please tell me how this is useful? I'm probably missing something and hence not seeing an immediate use of this? Thanks for the PR, though!

**Comment by beeant** [comment]
thank you for your response.
this is useful if you have set of collection data and you want to show the string inside the key property set in labelField. For example:

```javascript
var data = [{
  lower: "a",
  upper: "A"
}, {
  lower: "b",
  upper: "B"
}]:
```

with labelField option, you can set `lower` or `upper` to be shown.

without labelField, you can only show `text`

**Comment by prakhar1989** [comment]
Makes sense, @beeant. I had plans of giving more flexibility to the `suggestions` data, and this seems like a good fit. I'm not sure if I like the `labelField` term, but I'll merge this PR and change it later. I hope that's okay. I hope the component is useful to you :) Thanks!

**Comment by beeant** [comment]
@prakhar1989 thanks for the merge.
I take the labelField naming from selectize (http://brianreavis.github.io/selectize.js/)
I've been using selectize with angular.js, it seems to be matured, many ways to do customisation. but just it has jQuery dependencies.

**Comment by prakhar1989** [comment]
Ah ok. Didn't know about selectize. Looks good. Thanks for the link. :+1:

**Comment by prakhar1989** [comment]
> Use your left/right arrow keys to move the caret (ibeam) between items. (from selectize)

I really like this functionality. Looks much more usable than dragging items. What do you think?

**Comment by etosch** [comment]
@prakhar1989 : was this last comment meant for me or @beeant?

**Comment by prakhar1989** [comment]
Ah sorry for the confusion - it was meant for @beeant :)

**Comment by etosch** [comment]
Gotcha! I was following the thread and it occurred to me that you might be talking about something surveyman-specific, rather than a general design. (FWIW I always prefer using the keyboard over using the mouse, but I am probably in the minority of end-users in that way).

**Comment by prakhar1989** [comment]
> (FWIW I always prefer using the keyboard over using the mouse, but I am probably in the minority of end-users in that way).

Agree with you completely. That's the main reason why I really like the way `selectize` handles it. But since, you mentioned that the key users of surveyman are going to non-programmers, I felt that dragging might be more intuitive. If time permits, I'll really like to add this functionality as well.

**Pull request merged**
