### PR TITLE
feat(Tag and suggestions): Custom renderer for both tags and suggestions

### PR DESCRIPTION
**Pull request by cdreve**
I would like to be able to define a custom renderer function for both tags and suggestions. This
would give me a lot more control over how the tags and the suggestions are rendered.

re #309

### CODE REVIEW

**Comment by ad1992** [comment]
@cdreve instead of opening a new pr can you push this to the existing pr and reopen it?

**Comment by cdreve** [comment]
@ad1992 I made a new one because trying to rebase the old PR was a complete nightmare. Is it absolutely necessary?

**Comment by ad1992** [comment]
@cdreve can you force push this branch to the older branch then there wont be rebase issue, I would prefer the older PR since it has the conversations which happened during review. But its not straight forward then sure I will review this PR. no issues.

**Comment by ad1992** [comment]
@cdreve after your previous PR was closed, we received another pr https://github.com/prakhar1989/react-tags/pull/450 for adding render prop for suggestions which is currently in review. Can you remove the suggestion renderer for this PR ?

**Comment by ad1992** [comment]
@cdreve pls rebase as well with master so its easy to review

**Comment by cdreve** [comment]
@ad1992 Sorry for no response time. I was busy with something else. I hope to get the pull request ready this week.

**Pull request closed without merging**
