### PR TITLE
Added ability to handle a click event on a certain tag

### PR DESCRIPTION
**Pull request by SaharExelate**
Tags element supports handling a click event on a certain tag.
(This is needed in order to be able to identify which tag was clicked)

### CODE REVIEW

**Comment by oferitz** [comment]
@prakhar1989 any plans to merge it?

**Comment by mrdannael** [comment]
What about returning whole tag object onClick?

**Comment by SaharExelate** [comment]
I've implemented it the same behavior as the "delete click" behaves.
It returns the index of the tag in the tag array.
This way the clicks events of the component are aligned with same behavior

**Comment by mystetskyivlad** [comment]
@prakhar1989 any plans to merge it?
We really need this change. Because of this we needed to fork library and use this fork in our application.

**Comment by mrdannael** [comment]
I'll merge it today and release new version within 24 hours.

**Comment by cdreve** [comment]
@SaharExelate For me, the new version of react-tags throws `Uncaught TypeError: Cannot read property 'stopPropagation' of undefined` in the handleDelete method. This is when trying to delete a tag using the keyboard. Can you replicate this issue on your end?

**Comment by mrdannael** [comment]
@cdreve Should be fixed in v4.8.1. Try it now :)

**Comment by cdreve** [comment]
@mrdannael Yep, looks good. Thank you

**Pull request merged**
