### PR TITLE
Added support for onBlur event handling

### PR DESCRIPTION
**Pull request by Wildhoney**
Initial concept for https://github.com/prakhar1989/react-tags/issues/84

### CODE REVIEW

**Comment by prakhar1989** [comment]
This is absolutely fantastic Adam! Thanks a lot for sending in the PR and for adding the tests too! Merging this right away.

**Comment by Wildhoney** [comment]
Thanks @prakhar1989 &mdash; please let me know once published 👍

**Comment by prakhar1989** [comment]
Just published it! Thanks for your contributions again, Adam!

Also, I was wondering if you have any experience with [WebpackBin](http://www.webpackbin.com/). I've been trying to get this component set up as a bin to say that people can play with it before using it. But I've been running into a weird [issue](https://github.com/christianalfoni/webpack-bin/issues/160). Would you happen to have an idea of what's going on?

**Comment by Wildhoney** [comment]
Sorry &ndash; I'm not sure. It seems as though your module is setup in a typical way that `npm-extractor` expects &mdash; you have a valid `main` entry point.

**Pull request merged**
