### PR TITLE
add readOnly option

### PR DESCRIPTION
**Pull request by vkbansal**
Does not show `x` marks and input box in `readOnly` mode.

### CODE REVIEW

**Comment by prakhar1989** [comment]
Looks great, Vivek. Can you please document this feature in the README too?

**Comment by vkbansal** [comment]
Done

**Comment by aaronucsd** [comment]
I did an npm update and did not get the latest. I think i still see in package.json that it is 2.2.2, and i did not see any of the readOnly changes when i did the update nor did i get the updated version. I blew out he node_module too. I'm a missing something here?

**Comment by aaronucsd** [comment]
maybe bump the version and re-publish?

**Comment by prakhar1989** [comment]
Published on NPM. Thanks1

**Comment by aaronucsd** [comment]
good deal! Thanks guys! Making my job easier. And hopefully this is usefull for people not having to hack css and removeOCmponent etc to get readoOnly view. :)

**Pull request merged**
